In [1]:
# Imports
import numpy as np
import pandas as pd

In [2]:
# Loading Dataset and showing first 5 samples
df = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [26]:
# Checking memory usage
df.memory_usage(deep=True).sort_values(ascending=False)

PaymentMethod       475897
Contract            424701
customerID          415537
InternetService     389478
StreamingMovies     387867
StreamingTV         387842
OnlineBackup        387564
DeviceProtection    387557
TechSupport         387179
OnlineSecurity      387154
TotalCharges        386502
gender              380255
MultipleLines       371712
PhoneService        365554
PaperlessBilling    363364
Partner             362595
Dependents          361303
Churn               361062
tenure               56344
SeniorCitizen        56344
MonthlyCharges       56344
Index                  132
dtype: int64

In [27]:
df.sample(5, random_state=42)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No

In [3]:
# showing last 5 samples
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
# Showing column names
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [5]:
# Showing numerical columns
df.select_dtypes([np.number]).columns.tolist()

['SeniorCitizen', 'tenure', 'MonthlyCharges']

### Task 1

- What does each column represent?
- Which column is numerical?
- Which column is categorical?
- What is the Target?
- What does each business feature signify?

--- 

| Feature          | Description                                               |
| ---------------- | --------------------------------------------------------- |
| customerID       | Unique customer identifier (not used for prediction)      |
| gender           | Customer gender                                           |
| SeniorCitizen    | Indicates whether the customer is a senior citizen        |
| Partner          | Whether the customer has a partner                        |
| Dependents       | Whether the customer has dependents                       |
| tenure           | Number of months the customer has stayed with the company |
| PhoneService     | Whether the customer subscribes to phone service          |
| MultipleLines    | Whether the customer has multiple phone lines             |
| InternetService  | Type of internet service                                  |
| OnlineSecurity   | Subscription to online security service                   |
| OnlineBackup     | Subscription to online backup service                     |
| DeviceProtection | Subscription to device protection service                 |
| TechSupport      | Subscription to technical support service                 |
| StreamingTV      | Subscription to TV streaming service                      |
| StreamingMovies  | Subscription to movie streaming service                   |
| Contract         | Customer contract type                                    |
| PaperlessBilling | Whether paperless billing is enabled                      |
| PaymentMethod    | Customer payment method                                   |
| MonthlyCharges   | Monthly service charges                                   |
| TotalCharges     | Total amount charged during the customer lifetime         |
| Churn            | Target variable indicating customer churn                 |

In [6]:
# Showing the number of samples and feautures (+ target)
df.shape

(7043, 21)

In [7]:
# Checking the structure of Dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [8]:
# Description of Dataframe
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [23]:
# for object type datas
df.describe(include="object")

C:\Users\User\AppData\Local\Temp\ipykernel_3180\702551575.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [9]:
# Checking for duplicated values
df.duplicated().sum()

np.int64(0)

In [10]:
# Checking for NaN values
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [24]:
# Checking for unique values, count of them and value counts of each column
for col_name in df.columns:
    print(f'{col_name}: {df[col_name].unique()}')
    print('='*60)
    print(f'{col_name}: {df[col_name].value_counts()}')
    print('='*60)
print(df.nunique(axis=0))

customerID: <StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
============================================================
customerID: customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64
============================================================
gender: <StringArray>
['Female', 'Male']
Length: 2, dtype: str
============================================================
gender: gender
Male      3555
Female    3488
Name: count, dtype: int64
============================================================
SeniorCitizen: [0 1]
============================================================
SeniorCitizen: SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64
============================================================
Partner: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
============================================================
Partner: Partner
No     3641
Yes    3402
Name: count, dtype: int64
============================================================
Dependents: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
============================================================
Dependents: Dependents
No     4933
Yes    2110
Name: count, dtype: int64
============================================================
tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
============================================================
tenure: tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64
============================================================
PhoneService: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
============================================================
PhoneService: PhoneService
Yes    6361
No      682
Name: count, dtype: int64
============================================================
MultipleLines: <StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
============================================================
MultipleLines: MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64
============================================================
InternetService: <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
============================================================
InternetService: InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64
============================================================
OnlineSecurity: <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
============================================================
OnlineSecurity: OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64
============================================================
OnlineBackup: <StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
============================================================
OnlineBackup: OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64
============================================================
DeviceProtection: <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
============================================================
DeviceProtection: DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64
============================================================
TechSupport: <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
============================================================
TechSupport: TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64
============================================================
StreamingTV: <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
============================================================
StreamingTV: StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64
============================================================
StreamingMovies: <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
============================================================
StreamingMovies: StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64
============================================================
Contract: <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
============================================================
Contract: Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64
============================================================
PaperlessBilling: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
============================================================
PaperlessBilling: PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64
============================================================
PaymentMethod: <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
============================================================
PaymentMethod: PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64
============================================================
MonthlyCharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
============================================================
MonthlyCharges: MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
19.70     43
          ..
72.00      1
108.35     1
63.10      1
44.20      1
78.70      1
Name: count, Length: 1585, dtype: int64
============================================================
TotalCharges: <StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str
============================================================
TotalCharges: TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64
============================================================
Churn: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
============================================================
Churn: Churn
No     5174
Yes    1869
Name: count, dtype: int64
============================================================
customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [28]:
df["TotalCharges"].head(20)

0       29.85
1      1889.5
2      108.15
3     1840.75
4      151.65
5       820.5
6      1949.4
7       301.9
8     3046.05
9     3487.95
10     587.45
11      326.8
12     5681.1
13     5036.3
14    2686.05
15    7895.15
16    1022.95
17    7382.25
18     528.35
19     1862.9
Name: TotalCharges, dtype: str

TotalCharges
1      11
2      42
3      86
4     566
5    1358
6    2872
7    2108
Name: count, dtype: int64